- name: Configure client 
  hosts: client
  sudo: True
  tasks:
    - name: Install arora
      apt: name=arora state=present install_recommends=yes update_cache=yes
    - name: Install xubuntu
      apt: name=xubuntu-desktop state=present install_recommends=yes update_cache=yes
