- name: Configure client 
  hosts: client
  sudo: True
  tasks:
   - name: Install arora     
     apt: name=arora update_cache=yes
   - name: Install lxde
     apt: name=lxde state=present install_recommends=yes
   - user: name=client comment="My Client" 
           password='client'
