- name: Configure client 
  hosts: client
  sudo: True
  tasks:
   - name: Install arora     
     apt: name=arora update_cache=yes
   - name: Install xubuntu-desktop
     apt: name=xubuntu-desktop state=present install_recommends=yes
