---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Generate /etc/ssh/ RSA host key
      command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
      creates: /etc/ssh/ssh_host_rsa_key

    - name: Generate /etc/ssh/ DSA host key
      command : ssh-keygen -q -t dsa -f /etc/ssh/ssh_host_dsa_key -C "" -N ""
      creates: /etc/ssh/ssh_host_dsa_key

    - name: Generate /etc/ssh/ ECDSA host key
      command : ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C "" -N ""
      creates: /etc/ssh/ssh_host_ecdsa_key