- name: Configure client 
  hosts: client
  sudo: True
  tasks:
   - name: Install arora     
     apt: name=arora update_cache=yes
   - name: Install razorqt repository
     shell: add-apt-repository ppa:razort-qt
   - name: Install razorqt
     apt: name=razorqt state=present install_recommends=yes
