---
- hosts: database
  sudo: True
  tasks:
    - name: 1. Install MySQL server
      apt: name=mysql-server state=present
    - name: 2. Install MySQL python module
      apt: name=python-mysqldb state=present
    - name: 3. Move file for database
      copy:
       src: ~/virtualke/db.sql
       dest: ~/
